# Generated by Django 2.1.5 on 2019-03-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_song_lyrics'),
        ('users', '0002_comment_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='Nagranie'),
        ),
    ]
