# Generated by Django 2.1.5 on 2019-02-12 09:41

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Tytuł albumu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/Y%/m%/d%', verbose_name='Okładka')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Data założenia')),
                ('albums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Album', verbose_name='Albumy')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('instruments', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Wokal'), (2, 'Gitara klasyczna'), (3, 'Gitara elektryczna'), (4, 'Gitara basowa'), (5, 'Perkusja'), (6, 'Klawisze'), (7, 'Pianino'), (8, 'Skrzypce'), (9, 'Flet'), (10, 'Wiolonczela')], max_length=20, verbose_name='Instrumenty')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Tytuł piosenki')),
                ('duration', models.DurationField(verbose_name='Długość')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Tekst')),
                ('album_order_no', models.PositiveSmallIntegerField(verbose_name='Numer')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='musicians',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Musician', verbose_name='Muzycy'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Song', verbose_name='Piosenki'),
        ),
    ]
