# Generated by Django 2.1.5 on 2019-02-15 08:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/Y%/m%/d%', verbose_name='Zdjęcie zespołu'),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Blues', 'Blues'), ('Country', 'Country'), ('Elektroniczna', 'Elektroniczna'), ('Folk', 'Folk'), ('Hip hop', 'Hip hop'), ('Jazz', 'Jazz'), ('Klasyczna', 'Klasyczna'), ('Latynoska', 'Latynoska'), ('Pop', 'Pop'), ('R & B and soul', 'R & B and soul'), ('Rock', 'Rock')], default='Rock', max_length=30, verbose_name='Gatunek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/Y%/m%/d%', verbose_name='Okładka'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instruments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wokal', 'Wokal'), ('Gitara klasyczna', 'Gitara klasyczna'), ('Gitara elektryczna', 'Gitara elektryczna'), ('Gitara basowa', 'Gitara basowa'), ('Perkusja', 'Perkusja'), ('Klawisze', 'Klawisze'), ('Pianino', 'Pianino'), ('Skrzypce', 'Skrzypce'), ('Flet', 'Flet'), ('Wiolonczela', 'Wiolonczela')], max_length=107, verbose_name='Instrumenty'),
        ),
    ]
