# Generated by Django 2.1.5 on 2019-02-26 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190215_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='title',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Nazwa albumu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='name',
            field=models.CharField(default=None, max_length=128, verbose_name='Nazwa zespołu'),
            preserve_default=False,
        ),
    ]
