# Generated by Django 2.1.5 on 2019-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190226_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Blues', 'Blues'), ('Country', 'Country'), ('Elektroniczna', 'Elektroniczna'), ('Folk', 'Folk'), ('Hip hop', 'Hip hop'), ('Jazz', 'Jazz'), ('Klasyczna', 'Klasyczna'), ('Latynoska', 'Latynoska'), ('Pop', 'Pop'), ('R & B and soul', 'R & B and soul'), ('Rock', 'Rock')], default='Rock', max_length=30, verbose_name='Gatunek'),
            preserve_default=False,
        ),
    ]
