# Generated by Django 2.1.5 on 2019-02-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190227_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Song', verbose_name='Piosenki'),
        ),
    ]
