# Generated by Django 2.1.5 on 2019-02-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190227_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(default='janke', max_length=160, verbose_name='Imię'),
            preserve_default=False,
        ),
    ]
