# Generated by Django 2.1.5 on 2019-02-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190227_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='band',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='band',
            name='musicians',
        ),
        migrations.AddField(
            model_name='musician',
            name='band',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='music.Band', verbose_name='Zaspół'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='music.Album', verbose_name='Album'),
            preserve_default=False,
        ),
    ]
