# Generated by Django 2.1.5 on 2019-02-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='band_image',
            new_name='cover_image',
        ),
    ]
