# Generated by Django 2.1.5 on 2019-02-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190228_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data założenia'),
        ),
    ]
