# Generated by Django 2.1.5 on 2019-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20190311_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='', verbose_name='tekst nagrania'),
            preserve_default=False,
        ),
    ]
