# Generated by Django 2.1.5 on 2019-03-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='tekst nagrania'),
        ),
    ]
