# Generated by Django 2.1.5 on 2019-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20190312_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_play',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Przycisk odtwarzania Spotify'),
        ),
        migrations.AddField(
            model_name='band',
            name='spotify_follow',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Przycisk obserwowania Spotify'),
        ),
        migrations.AddField(
            model_name='band',
            name='spotify_play',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Przycisk odtwarzania Spotify'),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_play',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Przycisk odtwarzania Spotify'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/%Y/%m/%d', verbose_name='Okładka', width_field=385),
        ),
        migrations.AlterField(
            model_name='band',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/%Y/%m/%d', verbose_name='Zdjęcie zespołu', width_field=385),
        ),
    ]
