# Generated by Django 2.1.5 on 2019-03-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20190313_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/%Y/%m/%d', verbose_name='Okładka'),
        ),
        migrations.AlterField(
            model_name='band',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/%Y/%m/%d', verbose_name='Zdjęcie zespołu'),
        ),
    ]
