# Generated by Django 2.1.5 on 2019-03-13 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20190313_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2019)], verbose_name='Rok wydania'),
        ),
    ]
