# Generated by Django 2.1.5 on 2019-03-25 08:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20190313_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instruments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wokal', 'Wokal'), ('Gitara klasyczna', 'Gitara klasyczna'), ('Gitara elektryczna', 'Gitara elektryczna'), ('Gitara basowa', 'Gitara basowa'), ('Perkusja', 'Perkusja'), ('Klawisze', 'Klawisze'), ('Pianino', 'Pianino'), ('Skrzypce', 'Skrzypce'), ('Flet', 'Flet'), ('Wiolonczela', 'Wiolonczela')], max_length=107, null=True, verbose_name='Instrumenty'),
        ),
    ]
