# Generated by Django 2.1.5 on 2019-03-25 10:17

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20190325_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='spotify_play',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[music.models.validate_html], verbose_name='Przycisk odtwarzania Spotify'),
        ),
        migrations.AlterField(
            model_name='band',
            name='spotify_follow',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[music.models.validate_html], verbose_name='Przycisk obserwowania Spotify'),
        ),
        migrations.AlterField(
            model_name='band',
            name='spotify_play',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[music.models.validate_html], verbose_name='Przycisk odtwarzania Spotify'),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_play',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[music.models.validate_html], verbose_name='Przycisk odtwarzania Spotify'),
        ),
    ]
