# Generated by Django 2.1.5 on 2019-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/Y%/m%/d%', verbose_name='Zdjęcie'),
        ),
    ]
