# Generated by Django 2.1.5 on 2019-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_modification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='album',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='band',
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/%Y/%m/%d', verbose_name='Zdjęcie'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
