# Generated by Django 2.1.5 on 2019-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190222_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, height_field=400, null=True, upload_to='article_covers/%Y/%m/%d', verbose_name='Zdjęcie'),
        ),
    ]
