# Generated by Django 2.1.5 on 2019-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190313_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/%Y/%m/%d', verbose_name='Zdjęcie'),
        ),
    ]
