# Generated by Django 2.1.5 on 2019-03-25 10:17

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190313_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(validators=[music.models.validate_html], verbose_name='Treść artykułu'),
        ),
    ]
